export const buttons = [
  ['C', 'clear', 'clear', 'clear'],
  ['+/-', 'monoOperator', 'negate', 'negate'],
  ['%', 'monoOperator', 'percentage', 'percentage'],
  ['/', 'operator', 'divide', 'divide'],
  ['7', 'number', '7', 'seven'],
  ['8', 'number', '8', 'eight'],
  ['9 ', 'number', '9', 'nine'],
  ['x', 'operator', 'multiply', 'multiply'],
  ['4', 'number', '4', 'four'],
  ['5', 'number', '5', 'five'],
  ['6', 'number', '6', 'six'],
  ['-', 'operator', 'subtract', 'subtract'],
  ['1', 'number', '1', 'one'],
  ['2', 'number', '2', 'two'],
  ['3', 'number', '3', 'three'],
  ['+', 'operator', 'add', 'add'],
  ['0', 'number', '0', 'zero'],
  ['.', 'number', '.', 'decimal'],
  ['=', 'operator', 'equals', 'equals'],
];
